name: Automated Tests and Linting
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install

      - name: Run Typescript Checks
        run: yarn lint

      - name: Run Tests
        run: yarn test:ci

      - name: Build
        run: yarn build
