name: Automated Tests and Linting

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: yarn install
      - name: Build
        run: yarn build
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        run: yarn install
      - name: Run Typescript Checks
        run: yarn lint
      - name: Run Tests
        run: yarn test:cov
      - name: Run E2E Tests
        run: yarn test:e2e
